# Generated by Django 4.1.2 on 2022-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_alta', models.DateTimeField(verbose_name='Fecha de alta')),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('mobile', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
